[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'
solc_version = '0.8.31'
evm_version = 'osaka'
optimizer = true
optimizer-runs = 200

[lint]
exclude_lints = ["screaming-snake-case-immutable"]
